### ISSUE TITLE
[youtube] player `59b252b9`: nsig extraction failed: Some formats may be missing

### ISSUE THREAD

**Issue by Mehdioop** [yt-dlp/yt-dlp#13241]
### Checklist

- [x] I'm reporting that yt-dlp is broken on a **supported** site
- [x] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [x] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [x] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766), [the FAQ](https://github.com/yt-dlp/yt-dlp/wiki/FAQ), and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue%20-label%3Aspam%20%20) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

nsig extraction failed: Some formats may be missing
n = fMlnGpC7IEbpwqbdtnNh ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
nsig extraction failed: Some formats may be missing
May 21 12:10:47 snapshot--ubuntu-4gb-fsn1-2 bash[667]:          n = fMlnGpC7IEbpwqbdtnNh ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
May 21 12:10:47 snapshot--ubuntu-4gb-fsn1-2 bash[667]:          Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template
```

**Comment by rdamas** [comment]
Looks like #13238 addresses this issue.

**Comment by dmbsg** [comment]
I have got the same warning.

% ./yt-dlp_macos -U
Latest version: stable@2025.04.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.04.30 from yt-dlp/yt-dlp)

% ./yt-dlp_macos --verbose -R 800 --socket-timeout 10 --remux-video mkv -N 3  https://www.youtube.com/watch\?v=xz7kQthOlCQ
[debug] Command-line config: ['--verbose', '-R', '800', '--socket-timeout', '10', '--remux-video', 'mkv', '-N', '3', 'https://www.youtube.com/watch?v=xz7kQthOlCQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.04.30 from yt-dlp/yt-dlp [505b40079] (darwin_exe)
[debug] Python 3.13.3 (CPython arm64 64bit) - macOS-15.5-arm64-arm-64bit-Mach-O (OpenSSL 3.0.16 11 Feb 2025)
[debug] exe versions: ffmpeg 4.4.5 (setts), ffprobe 4.4.5
[debug] Optional libraries: Cryptodome-3.22.0, brotli-1.1.0, certifi-2025.04.26, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.49.1, urllib3-2.4.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1857 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=xz7kQthOlCQ
[youtube] xz7kQthOlCQ: Downloading webpage
[youtube] xz7kQthOlCQ: Downloading tv client config
[debug] Loading youtube-sts.59b252b9-main from cache
[youtube] xz7kQthOlCQ: Downloading tv player API JSON
[youtube] xz7kQthOlCQ: Downloading ios player API JSON
[youtube] xz7kQthOlCQ: Downloading player 59b252b9-main
WARNING: [youtube] xz7kQthOlCQ: nsig extraction failed: Some formats may be missing
         n = DoJ5YPUjzsv8YV7DWtm- ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
         Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Traceback (most recent call last):
  File "yt_dlp/extractor/youtube/_video.py", line 2322, in extract_nsig
  File "yt_dlp/jsinterp.py", line 928, in resf
  File "yt_dlp/jsinterp.py", line 241, in interpret_statement
  File "yt_dlp/jsinterp.py", line 394, in interpret_statement
  File "yt_dlp/jsinterp.py", line 241, in interpret_statement
  File "yt_dlp/jsinterp.py", line 599, in interpret_statement
  File "collections/__init__.py", line 1019, in __getitem__
  File "collections/__init__.py", line 1011, in __missing__
KeyError: 'smRLl34tByYhJ4B'
 (caused by KeyError('smRLl34tByYhJ4B')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] xz7kQthOlCQ: nsig extraction failed: Some formats may be missing
         n = 18bsQxr6GxLvnfLCldsH ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
         Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] xz7kQthOlCQ: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
WARNING: [youtube] xz7kQthOlCQ: nsig extraction failed: Some formats may be missing
         n = ImKIjhvGBL8ES6kBvu0E ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
         Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] xz7kQthOlCQ: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details

**Comment by dmbsg** [comment]
@bashonly After some time, I ran that command again. It worked flawlessly.

% ./yt-dlp_macos --verbose -R 800 --socket-timeout 10 --remux-video mkv -N 3  https://www.youtube.com/watch\?v=xz7kQthOlCQ
[debug] Command-line config: ['--verbose', '-R', '800', '--socket-timeout', '10', '--remux-video', 'mkv', '-N', '3', 'https://www.youtube.com/watch?v=xz7kQthOlCQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.04.30 from yt-dlp/yt-dlp [505b40079] (darwin_exe)
[debug] Python 3.13.3 (CPython arm64 64bit) - macOS-15.5-arm64-arm-64bit-Mach-O (OpenSSL 3.0.16 11 Feb 2025)
[debug] exe versions: ffmpeg 4.4.5 (setts), ffprobe 4.4.5
[debug] Optional libraries: Cryptodome-3.22.0, brotli-1.1.0, certifi-2025.04.26, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.49.1, urllib3-2.4.0, websockets-15.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1857 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=xz7kQthOlCQ
[youtube] xz7kQthOlCQ: Downloading webpage
[youtube] xz7kQthOlCQ: Downloading tv client config
[debug] Loading youtube-sts.804c67d2-main from cache
[youtube] xz7kQthOlCQ: Downloading tv player API JSON
[youtube] xz7kQthOlCQ: Downloading ios player API JSON
[debug] Loading youtube-nsig.804c67d2-main from cache
[debug] [youtube] Decrypted nsig ZjfjnXnusAWxT3M2ZSP => CL0hTQGAU2EvzA
[debug] [youtube] Decrypted nsig jvb_knGc8Bnw5i5CY_e => VH0RnoXGTgzUIw
[debug] [youtube] xz7kQthOlCQ: ios client https formats require a GVS PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a GVS PO Token for this client with --extractor-args "youtube:po_token=ios.gvs+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/PO-Token-Guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[youtube] xz7kQthOlCQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] xz7kQthOlCQ: Downloading 1 format(s): 337+251
[debug] Invoking http downloader on "https://rr2---sn-8ph2xajvh-83vl.googlevideo.com/videoplayback?expire=1747864521&ei=afctaObCAcrSv_IPocatgA8&ip=xxx&id=o-AGkPRkvkagoJ6IUlI2jQ5MEG_DE3rcFmYPZcMyEP9-sh&itag=337&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C330%2C331%2C332%2C333%2C334%2C335%2C336%2C337&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1747842921%2C&mh=ry&mm=31%2C29&mn=sn-8ph2xajvh-83vl%2Csn-n8v7kne6&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=23&rms=au%2Cau&initcwndbps=2246250&bui=AecWEAZOYneNsPzrvRc5pWdN12JafybbZ9tmNppQazAf45ijc0KQiFSWSYGKEuG0-AEI_21L8RwQnIqr&vprv=1&svpuc=1&mime=video%2Fwebm&ns=FNaFL5RMoF3cNk0KLItbqEoQ&rqh=1&gir=yes&clen=2137209101&dur=762.360&lmt=1744801450655463&mt=1747842562&fvip=13&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=6208224&n=VH0RnoXGTgzUIw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAKaf1-tRdim0ENkl7Kg9xHzzkxr-6TiMpWrDLUN7jqZPAiANd0GewHtTr_pwIJtZAZHI3nW2laPcxEObgkSjc77cmA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Crms%2Cinitcwndbps&lsig=ACuhMU0wRQIhALDTt68s9jmhifa5R2FhSTv3Dmg3_AGxTvJZZ0cgXaa3AiAaEuLCexpasA_nlwwaY6h9lcRltuc8C3u9knanl_Kkgw%3D%3D"
[download] Destination: 16K HDR NATURE IN UNSEEN CLARITY DOLBY VISION 60 FPS [xz7kQthOlCQ].f337.webm
[download] 100% of    1.99GiB in 00:04:42 at 7.22MiB/s
[debug] Invoking http downloader on "https://rr2---sn-8ph2xajvh-83vl.googlevideo.com/videoplayback?expire=1747864521&ei=afctaObCAcrSv_IPocatgA8&ip=xxx&id=o-AGkPRkvkagoJ6IUlI2jQ5MEG_DE3rcFmYPZcMyEP9-sh&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1747842921%2C&mh=ry&mm=31%2C29&mn=sn-8ph2xajvh-83vl%2Csn-n8v7kne6&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=23&rms=au%2Cau&initcwndbps=2246250&bui=AecWEAZOYneNsPzrvRc5pWdN12JafybbZ9tmNppQazAf45ijc0KQiFSWSYGKEuG0-AEI_21L8RwQnIqr&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=FNaFL5RMoF3cNk0KLItbqEoQ&rqh=1&gir=yes&clen=13151069&dur=762.381&lmt=1744160077892081&mt=1747842562&fvip=13&keepalive=yes&lmw=1&c=TVHTML5&sefc=1&txp=6208224&n=VH0RnoXGTgzUIw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgXgP0XgGDp0_L9smZIsP5OnNz9aP_Q0yEgexuI2R4WcACIBd_4mxl6YjYjR7ZoI1UIYvN9Rm7oGa0MHao74cz-xuV&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Crms%2Cinitcwndbps&lsig=ACuhMU0wRQIhALDTt68s9jmhifa5R2FhSTv3Dmg3_AGxTvJZZ0cgXaa3AiAaEuLCexpasA_nlwwaY6h9lcRltuc8C3u9knanl_Kkgw%3D%3D"
[download] Destination: 16K HDR NATURE IN UNSEEN CLARITY DOLBY VISION 60 FPS [xz7kQthOlCQ].f251.webm
[download] 100% of   12.54MiB in 00:00:01 at 7.33MiB/s
[Merger] Merging formats into "16K HDR NATURE IN UNSEEN CLARITY DOLBY VISION 60 FPS [xz7kQthOlCQ].webm"

**Comment by bashonly** [comment]
> [debug] Loading youtube-sts.804c67d2-main from cache

you got a different player

**Comment by gazmeist** [comment]
Ah I see this is being worked on. Shall wait patiently thanks team.

**Comment by bashonly** [comment]
@gazmeist 

It has already been fixed in the nightly channel.

```
yt-dlp --update-to nightly
```

**Comment by ylluminarious** [comment]
When can we expect a release of the fix on the stable channel, for those of us who use `yt-dlp` via a package manager?

**Comment by m4ttgit** [comment]
Is it fixed ?  I still run into the error with the updated nightly version. 

PS D:\Projects\whisper_gradio> yt-dlp --update-to nightly
Latest version: nightly@2025.05.21.232935 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2025.05.21.232935 from yt-dlp/yt-dlp-nightly-builds)
PS D:\Projects\whisper_gradio> python main.py
Loading Whisper model: medium...
Whisper model loaded.
Groq API key validation failed: Error code: 401 - {'error': {'message': 'Invalid API Key', 'type': 'invalid_request_error', 'code': 'invalid_api_key'}}
Continuing with local Whisper only.
* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.
[youtube] Extracting URL: https://www.youtube.com/shorts/7cfoMtZ7VKQ 
[youtube] 7cfoMtZ7VKQ: Downloading webpage 
[youtube] 7cfoMtZ7VKQ: Downloading tv client config 
[youtube] 7cfoMtZ7VKQ: Downloading tv player API JSON 
[youtube] 7cfoMtZ7VKQ: Downloading ios player API JSON 
WARNING: [youtube] 7cfoMtZ7VKQ: nsig extraction failed: Some formats may be missing 
         n = G4pEpfzprkaRyHkCEbxW ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
         Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] 7cfoMtZ7VKQ: nsig extraction failed: Some formats may be missing 
         n = 2zF7e0g-38OF8UK4bCgo ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
         Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] 7cfoMtZ7VKQ: nsig extraction failed: Some formats may be missing 
         n = VwySuBM53sUdPqymLYZZ ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
         Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] 7cfoMtZ7VKQ: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  https://github.com/yt-dlp/yt-dlp/issues/12482  for more details
[youtube] 7cfoMtZ7VKQ: Downloading m3u8 information
ERROR: [youtube] 7cfoMtZ7VKQ: Requested format is not available. Use --list-formats for a list of available formats

**Comment by coletdjnz** [comment]
> When can we expect a release of the fix on the stable channel, for those of us who use `yt-dlp` via a package manager?

shortly

**Comment by Trit34** [comment]
Still happens sometimes, even with the latest nightly release (nightly 2025.05.21.232935).

**Comment by bashonly** [comment]
@Trit34 try to get verbose output and share please

**Comment by Trit34** [comment]
Next time it occurs, because it’s not (yet?) systematic.

**Comment by m4ttgit** [comment]
> > Is it fixed ? I still run into the error with the updated nightly version.
> > PS D:\Projects\whisper_gradio> yt-dlp --update-to nightly Latest version: nightly@2025.05.21.232935 from yt-dlp/yt-dlp-nightly-builds yt-dlp is up to date (nightly@2025.05.21.232935 from yt-dlp/yt-dlp-nightly-builds) PS D:\Projects\whisper_gradio> python main.py Loading Whisper model: medium... Whisper model loaded. Groq API key validation failed: Error code: 401 - {'error': {'message': 'Invalid API Key', 'type': 'invalid_request_error', 'code': 'invalid_api_key'}} Continuing with local Whisper only.
> > ```
> > * Running on local URL:  http://127.0.0.1:7860
> > 
> > * To create a public link, set `share=True` in `launch()`.
> >   [youtube] Extracting URL: https://www.youtube.com/shorts/7cfoMtZ7VKQ
> >   [youtube] 7cfoMtZ7VKQ: Downloading webpage
> >   [youtube] 7cfoMtZ7VKQ: Downloading tv client config
> >   [youtube] 7cfoMtZ7VKQ: Downloading tv player API JSON
> >   [youtube] 7cfoMtZ7VKQ: Downloading ios player API JSON
> >   WARNING: [youtube] 7cfoMtZ7VKQ: nsig extraction failed: Some formats may be missing
> >   n = G4pEpfzprkaRyHkCEbxW ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
> >   Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> >   WARNING: [youtube] 7cfoMtZ7VKQ: nsig extraction failed: Some formats may be missing
> >   n = 2zF7e0g-38OF8UK4bCgo ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
> >   Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> >   WARNING: [youtube] 7cfoMtZ7VKQ: nsig extraction failed: Some formats may be missing
> >   n = VwySuBM53sUdPqymLYZZ ; player = https://www.youtube.com/s/player/59b252b9/player_ias.vflset/en_US/base.js
> >   Please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> >   WARNING: [youtube] 7cfoMtZ7VKQ: Some web client https formats have been skipped as they are missing a url. YouTube is forcing SABR streaming for this client. See  [[youtube] `web` only has SABR formats #12482](https://github.com/yt-dlp/yt-dlp/issues/12482)  for more details
> >   [youtube] 7cfoMtZ7VKQ: Downloading m3u8 information
> >   ERROR: [youtube] 7cfoMtZ7VKQ: Requested format is not available. Use --list-formats for a list of available formats
> > ```
> 
> Your script is using a different yt-dlp installation (probably via pip)

**Comment by nicolaasjan** [comment]
> Install [Deno](https://deno.com/) and [this yt-dlp plugin](https://github.com/bashonly/yt-dlp-YTNSigDeno) (maintained by me)

I hope that yt-dlp will not deprecate the use of Phantomjs, because Deno is **64bit** only and also requires Window 10 or higher.
So, my Python 3.9 builds of yt-dlp for XP, Vista and Windows 7 can not use it (I checked).
Phantomjs still does the job (I know it is not considered safe any more).
For XP, Phantomjs 1.9.8 will work (download [from Bitbucket](https://bitbucket.org/ariya/phantomjs/downloads/)).

**Comment by bashonly** [comment]
@nicolaasjan 

> I hope that yt-dlp will not deprecate the use of Phantomjs

We probably won't deprecate its use for nsig decoding. We have stopped recommending it, however. 

But nsig isn't the only thing that would necessitate an external JS interpreter dependency for YT downloads. It is looking like YT downloads will not be possible without PO tokens at some point in the future. I'm not sure how feasible a PhantomJS-based PO token provider is, or if anyone would want to write one... so when PO tokens are required across the board, you may need to find something else.
