### ISSUE TITLE
douyin.com extractor broken, Fresh cookies are needed

### ISSUE THREAD

**Issue by purple5pumpkin235** [yt-dlp/yt-dlp#2267]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

global

### Description

The douyin extractor is asking for cookies. I've only used this extractor once several months ago, and back then it didn't require cookies. 

`yt-dlp --cookies-from-browser firefox` also results in error.

Tested without logging in, because I don't have an account. 

### Verbose log

```shell
yt-dlp -Uv https://www.douyin.com/video/7049695447815818504
[debug] Command-line config: ['-Uv', 'https://www.douyin.com/video/7049695447815818504']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.11.0-44-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Optional libraries: secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [Douyin] Extracting URL: https://www.douyin.com/video/7049695447815818504
[Douyin] 7049695447815818504: Downloading video details
WARNING: [Douyin] 7049695447815818504: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[Douyin] 7049695447815818504: Downloading webpage
ERROR: [Douyin] 7049695447815818504: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 680, in _real_extract
    raise ExtractorError('Fresh cookies (not necessarily logged in) are needed')
```

**Comment by pukkandan** [comment]
I believe this has been fixed along with tiktok. Right, @MinePlayersPE

**Comment by AlexKLMan** [comment]
Sorry I don't really use Github that much, I see this is marked resolved but I don't see a fix? Did you find out what's wrong?

**Comment by bashonly** [comment]
you need to solve the puzzle piece captcha on the site and then pass your browser cookies to yt-dlp

**Comment by jidasheng** [comment]
Still unable to download, even with the attached cookies of being logged in (or not logged in).

**Comment by gohoski** [comment]
> Still unable to download, even with the attached cookies of being logged in (or not logged in).

Make sure the link is compatible and create a new issue

**Comment by bashonly** [comment]
@jidasheng @gohoski it's already being tracked in #9667
