### ISSUE TITLE
ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error

### ISSUE THREAD

**Issue by Donfu007** [yt-dlp/yt-dlp#2969]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Description
-------------------
I just installed yt-dlp on new Synology NAS which was working with youtube-dl...but very slow. This is a new box that I am trying to get youtube videos downloaded with the scheduler, nothing fancy or custom other than Plex is installed. 

On a scheduled task which worked with youtube-dl,  I replaced youtube-dl with yt-dlp.  

The script will run and fail 99% of the time with this error. If I rerun the task several times, the videos download is completed.
The URL of videos in this small sample I am trying to download is: https://www.youtube.com/c/TheDuracellProject/videos

I am sure this might not be a yt-dlp issue but not sure how to debug/solve this(new to synology also).

The script I am trying to run is:
---------------------------------------- 
#!/bin/sh
cd /volume1/PlexData/YouTube
yt-dlp  \
--dateafter now-1weeks \
--vU \
--download-archive /volume1/PlexData/YouTube/subscription_list_downloaded.txt \
-i \
-o "%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s" \
--add-metadata \
--write-thumbnail \
--batch-file=/volume1/PlexData/YouTube/subscription_list.txt

### Verbose log

```shell
[debug] Command-line config: ['--dateafter', 'now-1weeks', '-vU', '--download-archive', '/volume1/PlexData/YouTube/subscription_list_downloaded.txt', '-i', '-o', '%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s', '--add-metadata', '--batch-file=/volume1/PlexData/YouTube/subscription_list.txt']
[debug] Batch file urls: ['https://www.youtube.com/c/TheDuracellProject/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.8.8 (CPython 64bit) - Linux-4.4.180+-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.1.6
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] Loading archive file '/volume1/PlexData/YouTube/subscription_list_downloaded.txt'
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/TheDuracellProject/videos
[youtube:tab] TheDuracellProject: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/c/TheDuracellProject/videos
[download] Downloading playlist: The Duracell Project - Videos
[youtube:tab] playlist The Duracell Project - Videos: Downloading 22 videos
[download] Downloading video 1 of 22
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=EVowPDsY7KQ
[youtube] EVowPDsY7KQ: Downloading webpage
[youtube] EVowPDsY7KQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] EVowPDsY7KQ: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr2---sn-nx57ynls.googlevideo.com/videoplayback?expire=1646549993&ei=iQckYt7tGZWmkgbc95boCg&ip=24.113.11.109&id=o-APxCS_dvATUXM6O2EJE-J04kEp24056pZITN98CvYUGg&itag=248&source=youtube&requiressl=yes&mh=lT&mm=31%2C26&mn=sn-nx57ynls%2Csn-n4v7sney&ms=au%2Conr&mv=m&mvi=2&pl=20&initcwndbps=1593750&vprv=1&mime=video%2Fwebm&gir=yes&clen=123474318&dur=691.100&lmt=1646271963190109&mt=1646528204&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgEZg-rVVMLbBMMSgUYAnFG0WuJpCmYJwoEk4jKbRzPI0CIQCbYICx6ytPD3Aa9zvWuOuAcUay7PDvMrpv9UTzlP_fsA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPJ4JBzag4fN4NLdjvEu5U0atXkHuL2vHP6h-jV9_DN9AiBce-GOJK3nr6GcrPMNIM2Qi0vyqw4HtOt4qv49gRrOYg%3D%3D"
[download] Destination: The Duracell Project/The Duracell Project - Videos/The Duracell Project - Videos - S01E01 - Doghouse Roof Disaster Story [E19] [EVowPDsY7KQ].f248.webm

[download]   0.0% of 117.75MiB at 271.21KiB/s ETA 07:28
[download]   0.0% of 117.75MiB at 679.20KiB/s ETA 02:58
[download]   0.0% of 117.75MiB at  1.42MiB/s ETA 01:22 
[download]   0.0% of 117.75MiB at  2.79MiB/s ETA 00:42
[download]   0.0% of 117.75MiB at  1.62MiB/s ETA 01:12
[download]   0.1% of 117.75MiB at  1.93MiB/s ETA 01:00
[download]   0.1% of 117.75MiB at  2.73MiB/s ETA 00:43ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624)
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3068, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2801, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 372, in real_download
    return download()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 244, in download
    data_block = ctx.data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "/usr/lib/python3.8/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624)

[download] Downloading video 2 of 22
```

**Comment by Jules-A** [comment]
I've been getting this a lot when the the connection is flaky on Funimation but I get a slightly different error 

> [download]   3.0% of ~964.62MiB at 10.38MiB/s ETA 10:28 (frag 22/729)ERROR: unable to download video data: <urlopen error [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:997)>

**Comment by Donfu007** [comment]
Frustrating...I just clean installed DSM 7.0 on clean Synology 220+, clean installed Plex, clean installed yt-dlp and get the same error.  It cannot even make it through one URL before the error happens.

**Comment by Donfu007** [comment]
I think I found the isssue, if I set 

   --socket-timeout 60 

then is works.  I am sure 60 seconds is an overkill, but I can now download the files.

**Comment by pukkandan** [comment]
That is weird. The default is 20 secs even which is generally considered quite large with modern network speeds

**Comment by Donfu007** [comment]
Jules-A, correct.  As I use it more I am seeing it all the time now(thus reopened).  I cannot get through one video now.  I also tried retry but seems the code does not catch the exception and retry...but only fails.

At this time I do not see yt-dlp as an optional solution in my situation.  Will keep trying though to find a solution....

**Comment by krichbanana** [comment]
>  I also tried retry but seems the code does not catch the exception and retry...but only fails.

ssl.SSLError is an OSError, not an instance of urllib.error.HTTPError or urllib.error.URLError. It would have to be caught separately (and probably should, since it may be a transient error).

**Comment by Donfu007** [comment]
I agree 110% on the transient issue. Wish I knew this programming language and would submit a pull request but I'm coming from C# world so would have to bow to someone else hopefully doing this.  Seems like an easy fix. :-)

**Comment by coletdjnz** [comment]
The error is occurring during the reading of the response, so it does not get wrapped by urllib errors (which wraps errors during the request).

It would be nice to know what is causing this, but if we don't a simple fix would be to catch SSLError when reading the response. I don't think this would cause many issues, as e.g. certificate errors will occur during the request. 

```diff
diff --git a/yt_dlp/downloader/http.py b/yt_dlp/downloader/http.py
index 10ba61024..5b729a1dd 100644
--- a/yt_dlp/downloader/http.py
+++ b/yt_dlp/downloader/http.py
@@ -3,6 +3,7 @@ from __future__ import unicode_literals
 import errno
 import os
 import socket
+import ssl
 import time
 import random
 
@@ -256,7 +257,7 @@ class HttpFD(FileDownloader):
                     data_block = ctx.data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
                 # socket.timeout is a subclass of socket.error but may not have
                 # errno set
-                except socket.timeout as e:
+                except (socket.timeout, ssl.SSLError) as e:
                     retry(e)
                 except socket.error as e:
                     # SSLError on python 2 (inherits socket.error) may have

```

**Comment by pukkandan** [comment]
If anyone can confirm coledjnz's fix works, it can be committed

**Comment by Donfu007** [comment]
If someone can give me instructions on how, I'll be glad to do it.

**Comment by Jules-A** [comment]
> If anyone can confirm coledjnz's fix works, it can be committed

I'm trying but so far I've only seen http read errors which cause https://github.com/yt-dlp/yt-dlp/issues/2001 every time making the retry pointless...

**Comment by Donfu007** [comment]
@Jules-A , I've never worked in Linux, nor this language...I'm 30yr dev from Microsoft with C#. I am assuming you mean there is a file on the system that I can directly edit?

**Comment by krichbanana** [comment]
@Donfu007 
> I am assuming you mean there is a file on the system that I can directly edit?

There is, python code is generally in plain text.
This should find it, either quickly or eventually (ctrl-c to interrupt):
```bash
locate yt_dlp/downloader/http.py || find /usr/lib/python* ~/.local/lib/python* -path \*/yt_dlp/downloader/http.py || find -path \*/yt_dlp/downloader/http.py
```

Then you should be able to edit the file with `nano "(path)"` Add the import and change the 'except' line as noted in the earlier comment.

Alternatively, instead of editing with nano:
```bash
cd "(the directory containing yt_dlp)"
cat > fix.patch << EOF
(paste the patch from the earlier comment here)
EOF
git apply fix.patch
```

**Comment by pukkandan** [comment]
He's using the zip, so won't have the python files on disk
```
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
```

**Comment by Donfu007** [comment]
root@Coddiwomple:~# locate yt_dlp/downloader/http.py || find /usr/lib/python* ~/.local/lib/python* -path \*/yt_dlp/downloader/http.py || find -path \*/yt_dlp/downloader/http.py
-ash: locate: command not found
find: `/root/.local/lib/python*': No such file or directory

**Comment by Jules-A** [comment]
> root@Coddiwomple:~# locate yt_dlp/downloader/http.py || find /usr/lib/python* ~/.local/lib/python* -path */yt_dlp/downloader/http.py || find -path */yt_dlp/downloader/http.py -ash: locate: command not found find: `/root/.local/lib/python*': No such file or directory

You won't be able to edit the file directly since the version you are using is compiled. I mistakenly assumed you were using a different method. If you want to make the changes yourself you'll need to use a different method of install, personally I compile the exe using pyinst.py since it's super easy but you will Python, Pyinstaller, required dependencies and any optional dependencies. 
There's this 
```
py -m pip install -U pyinstaller -r requirements.txt
py devscripts/make_lazy_extractors.py
py pyinst.py
```

in the instructions which should do it all in one go.

**Comment by Donfu007** [comment]
@Jules-A , from the wiki documentation, this will build the Windows executable...I needed it on a Synolgy server(Linux) so don't think this will work.  Is there a chance someone can create a temp drop so I can do the usual:

sudo curl -L https://github.com/yt-dlp/yt-dlp/<DEBUG>/<DEBUG-DROP>/download/yt-dlp -o /usr/local/bin/yt-dlp

Seems that would be very useful for others wanting to test releases before they go into the release pipeline.

**Comment by Jules-A** [comment]
>from the wiki documentation, this will build the Windows executable...I needed it on a Synolgy server(Linux) so don't think this will work. 

>I've never worked in Linux

Ah this confused me so I assumed you meant the Windows Zip version. I have no experience with Linux outside of trying it out many years ago in a VM so I can't help you there, I'd just be repeating what's already available on the readme.md. If you were getting the socket errors contently you could always try the build to see if the patch fixed retries, I haven't triggered a socket timeout error since using it so I don't even know if it fixes the issue.

**Comment by Donfu007** [comment]
Finally got it to build on my windows machine to test it.  Problem is that I cannot duplicate it on my Win10 machine with the release build so can't hit this code path.  At this point, unless someone can give me a drop or clear instructions how I can get a linux build, I'm stuck verifying this.

**Comment by coletdjnz** [comment]
I've pushed the patch to [this](https://github.com/coletdjnz/yt-dlp-dev/tree/ssl-retry-fix) branch and triggered the GH action build for it

Unix binary is here: https://github.com/coletdjnz/yt-dlp-dev/releases/tag/2022.03.10.210744

Alternatively if you want to do this yourself, fork yt-dlp, apply the patch and run the build workflow github action.

**Comment by Donfu007** [comment]
Thanks @coletdjnz, I'll test this tonight.

**Comment by coletdjnz** [comment]
No need to run yt-dlp as root

I think you downloaded the webpage. try:
`sudo curl -L https://github.com/coletdjnz/yt-dlp-dev/releases/download/2022.03.10.210744/yt-dlp -o /usr/local/bin/yt-dlp`

`sudo chmod a+rx /usr/local/bin/yt-dlp`

**Comment by Donfu007** [comment]
Looks like it will functionally work (reminder, I do not get the error in Win10).  There are the expected errors.  I guess there are two take aways here:

1. Only print the error when it fails the complete download based on "ReTry", not each time...this will be confusing to users.
2. Why is this erorr happening in the first place.

Anyway, this unblocks me, thanks @coletdjnz and @Jules-A .

[debug] Invoking downloader on "https://rr2---sn-nx57ynse.googlevideo.com/videoplayback?expire=1646986800&ei=0LEqYpOGNaCQsfIPgcqTwAQ&ip=24.113.11.109&id=o-APHC4MwoAkOyAgNbo5xQpzLx2ZAbugpdV8lyszeGJIDb&itag=313&source=youtube&requiressl=yes&mh=-D&mm=31%2C29&mn=sn-nx57ynse%2Csn-nx5s7n7d&ms=au%2Crdu&mv=m&mvi=2&pl=17&initcwndbps=1785000&vprv=1&mime=video%2Fwebm&gir=yes&clen=1119636094&dur=855.754&lmt=1646946840590483&mt=1646965022&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgb6C-I7jAo2w0S-jvM3kfBaDsahQL21se-OCRgPOnWhsCIC9Nhwre05sgQI_sGULYr45Gz4ORuaP5emhpzSVjzXmE&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKeQAKoBfbdwP5MiVsm3JafFKZIfQm5lMq_KefcTZTdjAiBj69ekvwAz_KLYvDJFmDSd7hImpVX_VObr2_sl8sSJ6Q%3D%3D"
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  10.7% of 1.04GiB at 11.54MiB/s ETA 01:22[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 1 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  12.6% of 1.04GiB at  4.63MiB/s ETA 03:21[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 2 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  13.4% of 1.04GiB at 11.33MiB/s ETA 01:21[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 3 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  20.1% of 1.04GiB at 10.66MiB/s ETA 01:20[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 4 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  22.9% of 1.04GiB at  2.09MiB/s ETA 06:33[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 5 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  23.0% of 1.04GiB at  6.57MiB/s ETA 02:05[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 6 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  23.1% of 1.04GiB at  4.75MiB/s ETA 02:52[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 7 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  23.5% of 1.04GiB at  6.12MiB/s ETA 02:13[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 8 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  23.5% of 1.04GiB at  1.68MiB/s ETA 08:06[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 9 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  25.7% of 1.04GiB at  6.41MiB/s ETA 02:03[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 10 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  34.3% of 1.04GiB at  5.28MiB/s ETA 02:12[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 11 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  35.6% of 1.04GiB at  4.21MiB/s ETA 02:43[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 12 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  39.1% of 1.04GiB at  4.89MiB/s ETA 02:12[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 13 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  41.3% of 1.04GiB at  3.53MiB/s ETA 02:57[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 14 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  42.0% of 1.04GiB at  6.01MiB/s ETA 01:43[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 15 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  47.8% of 1.04GiB at  7.32MiB/s ETA 01:16[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 16 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  50.0% of 1.04GiB at  6.60MiB/s ETA 01:20[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 17 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  51.3% of 1.04GiB at  7.75MiB/s ETA 01:07[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 18 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  51.7% of 1.04GiB at  5.28MiB/s ETA 01:37[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 19 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  57.3% of 1.04GiB at  6.40MiB/s ETA 01:11[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 20 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  61.9% of 1.04GiB at  1.51MiB/s ETA 04:29[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 21 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  75.4% of 1.04GiB at 11.80MiB/s ETA 00:22[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 22 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  81.6% of 1.04GiB at 11.59MiB/s ETA 00:16[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 23 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  88.3% of 1.04GiB at 11.55MiB/s ETA 00:10[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 24 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  92.9% of 1.04GiB at  4.90MiB/s ETA 00:15[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 25 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download]  96.8% of 1.04GiB at  8.87MiB/s ETA 00:03[download] Got server HTTP error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] unknown error (_ssl.c:2624). Retrying (attempt 26 of 50) ...
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm
[download] 100% of 1.04GiB in 03:08
[debug] Invoking downloader on "https://rr2---sn-nx57ynse.googlevideo.com/videoplayback?expire=1646986800&ei=0LEqYpOGNaCQsfIPgcqTwAQ&ip=24.113.11.109&id=o-APHC4MwoAkOyAgNbo5xQpzLx2ZAbugpdV8lyszeGJIDb&itag=140&source=youtube&requiressl=yes&mh=-D&mm=31%2C29&mn=sn-nx57ynse%2Csn-nx5s7n7d&ms=au%2Crdu&mv=m&mvi=2&pl=17&initcwndbps=1785000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=13851153&dur=855.817&lmt=1646916734076106&mt=1646965022&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMiXcD072V2dn-j1eec1bG21E0Fm1odFfpT69xJTYUePAiAlLrpWAUwfUHgPQGUXzOSDKlPbd737cQktx1COFBwBcw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKeQAKoBfbdwP5MiVsm3JafFKZIfQm5lMq_KefcTZTdjAiBj69ekvwAz_KLYvDJFmDSd7hImpVX_VObr2_sl8sSJ6Q%3D%3D"
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f140.m4a
[download] 100% of 13.21MiB in 00:03
[Merger] Merging formats into "gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm' -i 'file:gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f140.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].temp.mkv'
Deleting original file gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f140.m4a (pass -k to keep)
Deleting original file gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].f313.webm (pass -k to keep)
[Metadata] Adding metadata to "gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E001 - TESTED - Hodgdon H4350 Powder [7utoCpEzZII].mkv' -map 0 -dn -ignore_unknown -c copy -metadata 'title=TESTED: Hodgdon H4350 Powder' -metadata date=20220309 -metadata 'description=Full Story: https://bit.ly/3w1fBG2
UR T-Shirts: https://bit.ly/2UEAkgW
UR on Patreon: https://www.patreon.com/ultimatereloader

**Comment by pukkandan** [comment]
The matter of retry can be tracked in https://github.com/yt-dlp/yt-dlp/pull/3059. Keeping this open because we still don't know the underlying issue

**Comment by pukkandan** [comment]
Outdates. Can be reopened if still reproducible
