### ISSUE TITLE
Dummies guide to installing plugins?

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#3204]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm start enough to do CLI and run yt-dlp, but apparently I'm not smart enough to get the "Youtube_AgeGateBypass.py" plugin working.

https://gist.github.com/pukkandan/fcf5ca1785c80f64e471f0ee14f990fb

I'm running yt-dlp from ${HOME}/bin/yt-dlp

Any help would be greatly appreciated.

Thanks.

**Comment by atom-smasher** [comment]
The good news is that's having an effect. The bad news is it's breaking things.

`find  ~/bin/ytdlp_plugins -type f`
```~/bin/ytdlp_plugins/extractor/__init__.py
~/bin/ytdlp_plugins/extractor/Youtube_AgeGateBypass.py
~/bin/ytdlp_plugins/extractor/__pycache__/__init__.cpython-38.pyc
~/bin/ytdlp_plugins/extractor/__pycache__/Youtube_AgeGateBypass.cpython-38.pyc
```

Got that. Not sure if I need to, but I made "__init__.py" and "Youtube_AgeGateBypass.py" executable.

`cat ~/bin/ytdlp_plugins/extractor/__init__.py`
`from .Youtube_AgeGateBypass import Youtube_AgeGateBypassIE`

And trying to download either an age restricted video, or a kitten video, I get errors:
`yt-dlp -vU  'https://www.youtube.com/watch?v=Ofge6a3gGis' `

```/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/atom/bin/yt-dlp/__main__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/__init__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/options.py", line 27, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/__init__.py", line 40, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/niconico.py", line 8, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/__init__.py", line 23, in <module>
  File "/home/atom/bin/yt-dlp/yt_dlp/utils.py", line 5103, in load_plugins
  File "/home/atom/bin/ytdlp_plugins/extractor/__init__.py", line 1, in <module>
    from .Youtube_AgeGateBypass import Youtube_AgeGateBypassIE
  File "/home/atom/bin/ytdlp_plugins/extractor/Youtube_AgeGateBypass.py", line 19, in <module>
    from yt_dlp.utils import get_first, parse_qs
ImportError: cannot import name 'get_first' from 'yt_dlp.utils' (/home/atom/bin/yt-dlp/yt_dlp/utils.py)

```

**Comment by atom-smasher** [comment]
The good news is that's having an effect. The bad news is it's breaking things.

`find  ~/bin/ytdlp_plugins -type f`
```
~/bin/ytdlp_plugins/extractor/__init__.py
~/bin/ytdlp_plugins/extractor/Youtube_AgeGateBypass.py
~/bin/ytdlp_plugins/extractor/__pycache__/__init__.cpython-38.pyc
~/bin/ytdlp_plugins/extractor/__pycache__/Youtube_AgeGateBypass.cpython-38.pyc
```

Got that. Not sure if I need to, but I made "__init__.py" and "Youtube_AgeGateBypass.py" executable.

`cat ~/bin/ytdlp_plugins/extractor/__init__.py`
`from .Youtube_AgeGateBypass import Youtube_AgeGateBypassIE`

And trying to download either an age restricted video, or a kitten video, I get errors:
`yt-dlp -vU  'https://www.youtube.com/watch?v=Ofge6a3gGis' `

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/atom/bin/yt-dlp/__main__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/__init__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/options.py", line 27, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/__init__.py", line 40, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/downloader/niconico.py", line 8, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/__init__.py", line 23, in <module>
  File "/home/atom/bin/yt-dlp/yt_dlp/utils.py", line 5103, in load_plugins
  File "/home/atom/bin/ytdlp_plugins/extractor/__init__.py", line 1, in <module>
    from .Youtube_AgeGateBypass import Youtube_AgeGateBypassIE
  File "/home/atom/bin/ytdlp_plugins/extractor/Youtube_AgeGateBypass.py", line 19, in <module>
    from yt_dlp.utils import get_first, parse_qs
ImportError: cannot import name 'get_first' from 'yt_dlp.utils' (/home/atom/bin/yt-dlp/yt_dlp/utils.py)
```

**Comment by pukkandan** [comment]
I have updated the plugin. Try again with the new version

**Comment by atom-smasher** [comment]
Beautiful!!

Thank you!!

**Comment by atom-smasher** [comment]
Whether I need it or not, I'm seeing `[youtube:AGB]` messages in the verbose output.

To respect the system resources of that proxy, how do I disable/enable it via config file and CLI?

I tried this, but I'm still getting `[youtube:AGB]` messages in the verbose output -
`VIDEO_PROXY=None yt-dlp -vU 'https://www.youtube.com/watch?v=Ofge6a3gGis'`

Exporting that as an environment variable still leaves the AGB extractor enabled.

I tried `--force-generic-extractor`, but that's not disabling it, either.

Or does it only engage itself when it's needed?

**Comment by pukkandan** [comment]
The proxy is used only when needed (You'll see a message `Downloading Zerody API ...` in console). But the plugin takes over all youtube downloads in order to determine whether to use the proxy or not. So `[youtube:AGB]` appearing always is normal. You can edit the `IE_NAME` if you wish

Please direct any further questions regarding that specific plugin to it's comment section. That said, don't expect to get the same level of support for the plugin as for this project

**Comment by pukkandan** [comment]
Please direct any further questions regarding that specific plugin to it's comment section. That said, don't expect to get the same level of support for the plugin as for this project
